name: yiitube

services:

  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      # Mount source-code for development
      - .:/app
    networks:
      - my_network

  backend:
    build: backend
    ports:
      - 8080:80
    volumes:
      # Mount source-code for development
      - .:/app
    networks:
      - my_network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - my_network

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

volumes:
  mysql-db:

networks:
  my_network:
    driver: bridge